### ISSUE TITLE
Sending arbitrary commands generaly does not work.

### ISSUE THREAD

**Issue by bassmanitram** [rene-d/sysbus#21]
```
> sysbus "Time: getTime"

erreur: {"result":{"status":null,"errors":[{"error":196618,"description":"Object or parameter not found","info":" getTime"}]}}
```

or

```
> sysbus Time: getTime

Traceback (most recent call last):
  File "/home/bartlett/.local/bin/sysbus", line 8, in <module>
    sys.exit(main())
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 1982, in main
    par_defaut(args.sysbus, args.parameters, args.raw)
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 1828, in par_defaut
    parameters[a[0]] = a[1]
```

The main command and some options work, though (with private info masked :) ):

```
> sysbus
     SoftwareVersion : SR40_sip-fr-3.63.8.1_7.21.3.1
              UpTime : 12 days, 11:06:12  (NumberOfReboots: 7)
   ExternalIPAddress : nn.nn.nn.nn
         IPv4Address : 192.168.1.1
         IPv6Address : ...
 IPv6DelegatedPrefix : ...::/56
         IPv6Address : ...
     directoryNumber : +nnnnnnnnnnn
```

**Comment by rene-d** [comment]
`sysbus Time:getTime`

**Comment by rene-d** [comment]
The correct syntax to query the internal datamodel is :
`sysbus <object>:<method> [arg=value ...]`

Example:
```bash
sysbus VoiceService.VoiceApplication:getCallList
sysbus VoiceService.VoiceApplication:clearCallList callId=226
```
Etc.



> ```
> > sysbus "Time: getTime"
> >              ^
No space here ;-)

There are typos in the English translation. I have tried to correct them - without guarantee - in release [1.0.4](https://github.com/rene-d/sysbus/tree/v1.0.4).


EDIT: rewrite in English for @bassmanitram

**Comment by bassmanitram** [comment]
Merci pour le fix - en fait je parle français aussi. :)
