### ISSUE TITLE
-graph is throwing an "option" error when attempting to execute the "dot" program

### ISSUE THREAD

**Issue by bassmanitram** [rene-d/sysbus#23]
This is probably due to the version of dot delivered with Ubuntu 16.04, which is 2.4:

```
dot: option -O unrecognized

Usage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>
(additional options for neato)    [-x] [-n<v>]
(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]
(additional options for memtest)  [-m]

 -V          - Print version and exit
 -v          - Enable verbose mode 
 -Gname=val  - Set graph attribute 'name' to 'val'
 -Nname=val  - Set node attribute 'name' to 'val'
 -Ename=val  - Set edge attribute 'name' to 'val'
 -Tv         - Set output format to 'v'
 -Kv         - Set layout engine to 'v' (overrides default based on command name)
 -lv         - Use external library 'v'
 -ofile      - Write output to 'file'
 -q[l]       - Set level of message suppression (=1)
 -s[v]       - Scale input by 'v' (=72)
 -y          - Invert y coordinate in output

 -n[v]       - No layout mode 'v' (=1)
 -x          - Reduce graph

 -Lg         - Don't use grid
 -LO         - Use old attractive force
 -Ln<i>      - Set number of iterations to i
 -LU<i>      - Set unscaled factor to i
 -LC<v>      - Set overlap expansion factor to v
 -LT[*]<v>   - Set temperature (temperature factor) to v

 -m          - Memory test (Observe no growth with top. Kill when done.)
Traceback (most recent call last):
  File "/home/bartlett/.local/bin/sysbus", line 8, in <module>
    sys.exit(main())
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 1969, in main
    args.run_auth(a)
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 1679, in graph_cmd
    dot.render(filename="nemo_intf.gv", view=view)
  File "/home/bartlett/.local/lib/python3.5/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/home/bartlett/.local/lib/python3.5/site-packages/graphviz/backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/bartlett/.local/lib/python3.5/site-packages/graphviz/backend.py", line 172, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tsvg', '-O', 'nemo_intf.gv']' returned non-zero exit status 1 [stderr: b"dot: option -O unrecognized\n\nUsage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>\n(additional options for neato)    [-x] [-n<v>]\n(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]\n(additional options for memtest)  [-m]\n\n -V          - Print version and exit\n -v          - Enable verbose mode \n -Gname=val  - Set graph attribute 'name' to 'val'\n -Nname=val  - Set node attribute 'name' to 'val'\n -Ename=val  - Set edge attribute 'name' to 'val'\n -Tv         - Set output format to 'v'\n -Kv         - Set layout engine to 'v' (overrides default based on command name)\n -lv         - Use external library 'v'\n -ofile      - Write output to 'file'\n -q[l]       - Set level of message suppression (=1)\n -s[v]       - Scale input by 'v' (=72)\n -y          - Invert y coordinate in output\n\n -n[v]       - No layout mode 'v' (=1)\n -x          - Reduce graph\n\n -Lg         - Don't use grid\n -LO         - Use old attractive force\n -Ln<i>      - Set number of iterations to i\n -LU<i>      - Set unscaled factor to i\n -LC<v>      - Set overlap expansion factor to v\n -LT[*]<v>   - Set temperature (temperature factor) to v\n\n -m          - Memory test (Observe no growth with top. Kill when done.)\n"]

```

**Comment by rene-d** [comment]
Weird... I have tried with a Docker image of Ubuntu 16.04 :
```
root@cff34bbbd835:/# lsb_release -dr
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
root@cff34bbbd835:/# dot -V
dot - graphviz version 2.38.0 (20140413.2041)
```

**Comment by rene-d** [comment]
I do not invoke `dot` directly but through the [graphviz](https://pypi.org/project/graphviz/) Python package. So I can't fix this error.

Maybe you have a very old version of `graphviz` in your PATH. Ubuntu reports as I have mentioned above the version [2.38 for Ubuntu xenial](https://packages.ubuntu.com/xenial/graphviz).

If you cannot (or don't want to) upgrade your system, you can try a Docker container.
