### ISSUE TITLE
sysbus -modeluml throws an error when no class or object is specified 

### ISSUE THREAD

**Issue by bassmanitram** [rene-d/sysbus#24]
This may just be madness on my part, but  since `sysbus -model` works I think this should work too. So, when running

```
sysbus -modeluml
```

(i.e. no class or object name)

```
$ sysbus  -modeluml
Traceback (most recent call last):
  File "/home/bartlett/.local/bin/sysbus", line 8, in <module>
    sys.exit(main())
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 1957, in main
    model_uml_cmd(args.sysbus, prof, out=args.out)
  File "/home/bartlett/.local/lib/python3.5/site-packages/sysbus/sysbus.py", line 840, in model_uml_cmd
    debug(2, "créatoin répertoire: " % "models")
TypeError: not all arguments converted during string formatting

```

**Comment by rene-d** [comment]
Ok, it's easy to fix.
```
-            debug(2, "créatoin répertoire: " % "models")
+            debug(2, "création répertoire: %s" % "models")
```

I haven't tested nor used this for a long time. It seems to continue to work fine.

Thanks 👍
