### ISSUE TITLE
Support LiveBox 5

### ISSUE THREAD

**Issue by BrunoLabidoire** [rene-d/sysbus#35]
Bonjour, y-a-t-il une chance que la LB5 soit supportée ou est-elle trop différente au niveau Firmware? Merci

**Comment by rene-d** [comment]
Bonjour, ça fonctionne avec la lb5.

**Comment by rene-d** [comment]
je ferme

**Comment by BrunoLabidoire** [comment]
Alors je dois avoir un autre problème…

 

Ca marchait bien avec mon ancienne Box mais depuis la LB5 j’ai le même problème que ce soit sous Windows ou sous Linux.

 

Une piste ?

 

Merci

Bruno

 

m:\Keys>sysbus -hosts

Traceback (most recent call last):

  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "c:\python37\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "C:\Python37\Scripts\sysbus.exe\__main__.py", line 9, in <module>

  File "c:\python37\lib\site-packages\sysbus\sysbus.py", line 1951, in main

    if not auth(new_session):       # initialise la session requests avec authentification

  File "c:\python37\lib\site-packages\sysbus\sysbus.py", line 300, in auth

    if not 'contextID' in r.json()['data']:

  File "c:\python37\lib\site-packages\requests\models.py", line 897, in json

    return complexjson.loads(self.text, **kwargs)

  File "c:\python37\lib\site-packages\simplejson\__init__.py", line 518, in loads

    return _default_decoder.decode(s)

  File "c:\python37\lib\site-packages\simplejson\decoder.py", line 370, in decode

    obj, end = self.raw_decode(s)

  File "c:\python37\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode

    return self.scan_once(s, idx=_w(s, idx).end())

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 

m:\Keys>

 

 

***@***.***:~$ sysbus -hosts

Traceback (most recent call last):

  File "/usr/local/bin/sysbus", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.8/dist-packages/sysbus/sysbus.py", line 2001, in main

    if not auth(new_session):       # initialise la session requests avec authentification

  File "/usr/local/lib/python3.8/dist-packages/sysbus/sysbus.py", line 300, in auth

    if not 'contextID' in r.json()['data']:

  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json

    return complexjson.loads(self.text, **kwargs)

  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads

    return _default_decoder.decode(s)

  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode

    obj, end = self.raw_decode(s)

  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode

    return self.scan_once(s, idx=_w(s, idx).end())

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

***@***.***:~$

 

De : rene-d ***@***.***> 
Envoyé : vendredi 8 avril 2022 17:08
À : rene-d/sysbus ***@***.***>
Cc : BrunoLabidoire ***@***.***>; Author ***@***.***>
Objet : Re: [rene-d/sysbus] Support LiveBox 5 (Issue #35)

 

Bonjour, ça fonctionne avec la lb5.

**Comment by rene-d** [comment]
Hello,

une partie a fonctionné avec les lb5, mais ils ont _encore_ changé des trucs... du coup effectivement ça ne fonctionne plus :(

A moins de creuser, chercher  et corriger, ce projet va devenir obsolète 🫢
